version: '2'

networks:
    user-facing:
      driver: bridge
    service-facing:
      driver: bridge

services: 

    webserver: 
        image: webserver
        build: ./webserver
        ports:
            - 8000:80
        networks: 
            - user-facing

    goservice: 
        image: goservice
        build: ./goservice 
        ports:
            - 8080
        networks: 
            - service-facing

    proxy:
        image: dockercloud/haproxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:80        
        links:
            - goservice
        networks:
            - user-facing
            - service-facing